source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '3.0.10'
gem 'mysql', '2.8.1'
gem 'airbrake'
gem 'haml', '3.1.0'
gem 'haml-rails', '>= 0.3.4'
gem 'will_paginate', '~> 3.0.pre2'
gem 'jquery-rails', '0.2.7'
gem 'paperclip', '2.3.11'
gem 'devise', '1.3.3'
gem 'hpricot', '0.8.4'
gem 'ruby_parser', '2.0.6'
gem 'twitter', '1.4.0'
gem 'cap_gun', '0.2.4'
gem 'hoptoad_notifier', '2.4.9'
gem 'settingslogic', '2.0.6'
gem 'atom-tools'
gem 'tiny_mce'
gem 'hashie' ,'1.0.0'
gem 'rails_admin', :git => 'git://github.com/sferik/rails_admin.git', :branch => 'rails-3.0'
gem 'static_model', '1.0.2'
gem 'aws-s3'
gem 'tropo-webapi-ruby', '0.1.9'
gem 'nested_form'

group :development do
  gem 'rspec-rails', '>= 2.2.1'
  gem 'capistrano'
  gem 'ruby-debug19'
end

group :test do
  gem 'factory_girl_rails', '1.0'
  gem 'fakeweb', '1.2.8'
  gem 'rspec-rails', '>= 2.2.1'
end
